version: '3.8'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3307:3306"
